apiVersion: v1
kind: Secret
metadata:
    name: client-info-secret
    namespace: synology-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:374mVBJDFQo1lhwTF2J4xMInNjVKzpYShSn5duWVgEQARl1bvyC0kDrLlye+D6ehWxHmKzIbDnMkWnAERSfD1FgtvFVQOJ9vJQUo6Pt6LGLa/sXmJq4/vJfi/1fK5LgvsKhdn+ibR0dgaiwqUBM3UctQnKt7xo9xB9RHHbFCkjCujZfYaBcn7NXdWcU8SbKbjo9wr1C1dejwul3mFYXZ/AQBF7IcxOfrLmf3gQwY0THsnOPyzfcY1kFHMCRgrv0uR1AbB24DsGDrGTrx0YpxZDCTsgQO+i/p9dReXBKw1FYw4lL3EkVWAg==,iv:JcBR5phoU29v9xljhBzykwA/HSDYBDyLBtX5G11p+IQ=,tag:5t8cYZfylsXV31GxAIqVdw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMTFuSEdMZGZMWWM1eTND
            ZHlQMmJoUk5wQWcwTGRVK25lRjdMeHFUclVNCjdxalIxak91cUlEZlEwMHVhZEdw
            QWY4cGljQzN4cVpnQjVBK01NWDlScjQKLS0tIEpiQVBzUHBKMXpmTXE4MFdJMXZm
            alFrN2JydmN3eUpVRzYyWVNscjduQjgKACBFolIpYSa4mQ4E7o9uq25FlFn6ICU1
            J4jZi1zhhDiQcAg0qmn/aFsE5UgxOxE3OGZNhWO+B12WlcyP48n9iQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13rglp49t3fzw0q4wq2n9y4g4dgsdv3nc5tzwetnrzjc4nx3z3gwqnd2nzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:30:25Z"
    mac: ENC[AES256_GCM,data:HJVdzTTJTzDANATK/lUqO3emzG8gdjVYJuZbT/ze8EXyRTtYSup6z++W4mZwTU7dwFDZrqt+n3N6LDH4cjkPTAa9+PucHIaDpeWrwPR8kQR1JjipPnoIspCPH3mSDys0HiKXe2RgVswRtr6HC+Sr1rJDpt5xW9w294K5Drt+vEU=,iv:aN/lO+XEgDFvJs6hKiqCUOFG8xvHlPY+wl4JdIUQNGI=,tag:0Teqk7s/AWV7AINuHWhChw==,type:str]
    version: 3.13.3
