apiVersion: batch/v1
kind: Job
metadata:
  name: minio-buckets
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-root-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-root-secret
                  key: MINIO_ROOT_PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              until mc alias set local http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
                sleep 2
              done
              mc mb --ignore-existing local/kan-avatars
              mc mb --ignore-existing local/kan-attachments
              mc anonymous set download local/kan-avatars
              mc anonymous set download local/kan-attachments
