apiVersion: v1
data:
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZGU8Jvs0gIcxy2nVSGFvInc2x1cbpNA65khO7Q==,iv:Xk4I/elumJ7YARRRoO7gC7MzbWrJPaePn0jfBoaC4yM=,tag:DQas1c1jQJ8zKZanNGQKtA==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bkFSruSOfG4mkHnEJ/JBRnatstO6TMATdYXdBJLNZ6Deh/3mcjl0HOTii6eEcUxGNerQp0eaTxCG5vZB,iv:h3FoBzCT5AU2n3Ab1iCx4NICI5gq43BeAyxQxlm/6Z0=,tag:eB8pZjdnVevWLybVdx4oCg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kan-s3-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZ2kwdzh0dkxEcC84NVo0
            YnlSbGRDSDQ5VWw5cVFlVUhldlNjSkh4clNBCk55VXM0cUo1ek1ncnRXVWM2NkNy
            WCtyY0Fqd2R5OXZoM010ZEJESEEvZ2MKLS0tIHhKK3NhTjAzdzBJQXhjc1BNTUtj
            aFQwOGhWajVuT091WnhtWUpndjd3eTgKvDD9/RX/tM15cz8hUQwWSOLm/G13e0Zh
            OBrAbuKvry1bXmv57d8iGQJegdMhx0NwLae1R590Ngs9IyI4n+dP6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13rglp49t3fzw0q4wq2n9y4g4dgsdv3nc5tzwetnrzjc4nx3z3gwqnd2nzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:30:24Z"
    mac: ENC[AES256_GCM,data:0hRXBVY+FH+VBWA2piyZx0k1Rco68s9rReMK/5SZo0zW5X85dIGZ2ecpr2PZGJa545jHy/jVrfZGvmXkMUtGobw2o4rJn7XETSe4yxHiWgY4CTfApsV7/b7HC8Itf9xo7t6gWAJYAzFR1HDRLCP5/dvvga5pPnffV/2Fin1rbSw=,iv:ZV8eDpDqkvDafYDktSi/gW77tOCfT2IT/Avp9TBx9us=,tag:O77ShBT8L+cUzGrmVfkWbQ==,type:str]
    version: 3.13.3
