apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:E9hoA0xyc77YrwQPE4OdItpPD8C7GsAv/JfOnjRrcBnMjT08d4RUPKZ6BYQ=,iv:RddYPtncK6MDvMUiiGCFRGTAOavc5HUs7o9OybalUXo=,tag:bVQwvjValH13QVWEo8pAcQ==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:VpYgwKK1b+tp5SqI9JPp3YoWJfo+9e5RTVavGgGAMBEJtDUGCwf+fRv8Xjt3eOXOknWwLV/2ZZ8Kby3Z,iv:ZZ1NLPFBquDcEeiqyFy8Pn+qNgzveoegXbmo42tQ1mU=,tag:DRzqdVBmeWCNvBGZG1UYZQ==,type:str]
kind: Secret
metadata:
    name: kan-secret
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUGVTaFJHM2M3NE1rbHJG
            VWZzcnZBUlg5UzBuZU9uWG56RUE4T0pKL2lrCmRMREhEVGRXRUNpOE5KVHJhbE83
            bmYrY05rV002b05EaDFuVzRKaEJYTWsKLS0tIHhxdGdqL0s4MjUxYzF4Y1pDcVFI
            cjYybW5lMDVFSXdVVTJrcGhrMmE3UTgKJwbdG13qwMPJC87fXZRb0MPnXA61TsRG
            Rm1Z+XsKHbbtKbi5P7gXse0z1HiD8BCzxAuvv/xEXCDA7rsg83qsfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13rglp49t3fzw0q4wq2n9y4g4dgsdv3nc5tzwetnrzjc4nx3z3gwqnd2nzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:30:24Z"
    mac: ENC[AES256_GCM,data:zxnL16ksGqb01A6TufIDTD+2rsCDXCEtoLHWsHUFvs3dX5c+1S+RevYg4ZRXbH8auVpjdGszh/uyBvSV6wfYf2XIf7MDdGeGbVODqOcV17ssvt+WnHYD9DrOoHFl2vyP9zN2vfXYJ+ZfJLSU3K7j3ohejMIMKqlOYswVu9WsHW4=,iv:gB7ASMRzgOdS8Ohl7s8+E0o6vScD75QdSHL5dFcJuLc=,tag:Rcxx9vivDdAKfGcQjQjJRg==,type:str]
    version: 3.13.3
