apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5SanWe/FE9pSu7sEsi81YBjXMDaJvY64pkyXuzoqIYtUs/S7xCBbXsOCr0o=,iv:UJ9u3gHG9vMRSJx9H1RIexr07pEwylbhX4lvtS47UK0=,tag:2r8ICNkIub727gKf6FwM/w==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:Zvf8B1elZJLZKcNIcqv5dgP1pr1ENF4mHDB5/vhZV4C06T8/P1lojv7kScjB/6sfkWhpLnFF7san/Z+9,iv:Z6T5fsiq7dMqbsik2LHpuFNrwf0SFX0jCDS2GaSRydA=,tag:TMhPc+ZDIih4Agnc1foYiQ==,type:str]
kind: Secret
metadata:
    name: kan-secret
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSENGMVhodWk2VCtlVnJi
            RE5zU0VnQ21sdVFmblBzR0NMcFp1WFJzTGtZCngrS3FQWVI2dlBiVWo5K0thclE4
            bjNkZzB4eGhoL3hQMXpCR1NwLzRvWkkKLS0tIE9NeGI3VGNtdTR5SlVuT1R0bmFu
            NTA0RkpRei9VMVZGUlFwTkw3djdSSDgK5tbER2QhtMrBUdgh5KbVk/dQ2lHG9CYd
            v/eOPpIgtvTY3ttp+9nFcKYhmX/stRFpk8mr+JeHwonF5Cp6Ges3pA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19fd7xlck0r3645chqjxq2m22qmtmatr4g0yghplsm33cn5yq7fuq69734h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T13:44:17Z"
    mac: ENC[AES256_GCM,data:S3+G7plTKiCQ615dgF/f3KuW6OFHtWtG3Gz1wol7p6+vokNrDiZ1ZMZwri+KK3TKylCufIx0nf2lEk/bXHskA3I4xtL42n3ygBq8aLBcxovtEHNm+dBeQcyWk3s0yhE7ApM2sWX94MZV3s0vtESitGlyucZB3hCrcnQGTAATuIU=,iv:HbFnnVIi/kFHAPAiO0gfJkWb6iGWN9kZe5l+7sPpRoc=,tag:V1vA34RrkEsHcFvplQJOng==,type:str]
    version: 3.13.3
