apiVersion: v1
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:S5njpahuAV6j/PwEflVS3GQ+TZUSZ1q+Hrt2QhmUb2Ea1jblIWFzH3eIcbU=,iv:LQrXoHU1hpuoSYjI1bQhi4c8HT3gFatr7PX9Rv1xrdw=,tag:bOdhvL7h2vvZ3jR3KRnGPA==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:pI0Zx9gFv0l8fOf9+GmGqj8NxIlfT44qUee2EdufUfSYnQVddFnw8yMPDeoN5aDbqrxBPSmAtcOyDiqv,iv:V+1Kl7ASR+ayKu7ClDMQciycZT+7TDKh0DY7bvVqhOs=,tag:5uVn9SaYtbO8i4QtssPqcQ==,type:str]
kind: Secret
metadata:
    name: kan-secret
sops:
    age:
        - recipient: age19fd7xlck0r3645chqjxq2m22qmtmatr4g0yghplsm33cn5yq7fuq69734h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSW5rODJLbGVxUWZ6aDRq
            QUpSWDVYK3ljSFJQalB4OXNidWRXTy9EYlJBCkxqODVDNnQ5QUorYzIxS3JjTWlJ
            SDd3WWE0NkVzUDU2SnVTNzZ5WEx1aHMKLS0tIGRDRUFIVG5DdzBzTWlVTmFhUGVn
            dXB2SDdwM2toYVdLS1pnUWdhcnNoTjgKuHo/v203ExYdYy3jRmZB8d0LXhLKAklG
            rJWJyzoSM9edxvXsvDZska3dFKjtxKgyc/vax4NaoEhNdBcVK+yxkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T15:50:25Z"
    mac: ENC[AES256_GCM,data:PKuuGxf76uuRxlrlloxuMQOi66dMgP4OshNbZaXF9ooU1yt3BoOVvLNYMYvfhQ6mi3PKNXZ+NcI2Dfv/QFTk8i6iW6Lm5qzo+WqvxuFTZpD+EdE26A/VhKydOe0n28tRtxejve2hWiIy63kbN0xuSk++Q6sDybOd9CTiBXlQtC4=,iv:5VK6gQjWkHiuBFD5klvOpF/j75RQGHUXfr9C7iIsS9Q=,tag:5vnStSxZVL8GfjIuESeykQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
