apiVersion: v1
data:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:+yN/0t9L+lVeIDtUfyGpOyZwSs+vhBs46Ij91w==,iv:VHW3e6ZrEix7s7UrOkDKxevtJ0XQqXMCZ6kvs7jsru4=,tag:oqqLG3E4hX/UYVkW4Tk0Zw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:jHq1kHTUQbth2lz2asl42iLKI3I5yb9lh5JynobE0QWe5R/wmEidmsBPS5ULaf8KfSu0lcYIE+i+X1Ac,iv:NU6sloaljgpOSeKLRNMfgRYkluJwXSwttTeYnTXQXog=,tag:SIMkeu2LewBJgqLeZIcFaA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: minio-root-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcHljaDdSb2xRejh0Mnl4
            VEhNQk5iZmFZNzNKTUlodHlXdnlTSE9oQlF3CmFOc0ZnMGFoN2FxQmpsdTYyQU0r
            a2NCb3NCK0dqc0NQVlk1TDd3eFV0TjQKLS0tIG82ai8wQU5yTEdLMGNpV1VHUXpk
            VHkyR1dTSm9tMzlCTmlVbTZXbExGcVEK3NNhOz06HKndarnwizFfEituFoRVOR38
            ufGOYDE0JyxEG6jV551E839Kv64RlwPCiKk+7/S0FRCUi3BzfV212g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13rglp49t3fzw0q4wq2n9y4g4dgsdv3nc5tzwetnrzjc4nx3z3gwqnd2nzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:30:25Z"
    mac: ENC[AES256_GCM,data:LwVWziY6hpG6s9xHRbpxnSa5gOZApajaFTsI6Zbx0NTeU+UJLqXOu8fTKEfZlqaprymp+jKFPUuV3TQrtvjRaX3nCzYbrzsVAwSi3BBAfHLu50b8jUhUEkumD40CmCxjSqWBO0xC3BlNP90L5z8QvH3QON0Z4dMUGftYWobwYpI=,iv:Z3wOxc/8Rwt2qTmv671XJsrCiKzAInPc3vduXZAjxCc=,tag:uINK+bciFw8TYeb6/3e00A==,type:str]
    version: 3.13.3
