apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:RMMAID2I7eLr9frDkTHNuq9wZt8Nn103x8JTVp1g5QnVWQCYjdgflamc0tYmRDlNFx7I0snIaufLJnADtm6IIOGcsoq+ythwA+/id4BcNC5wzVcnS5hFoTlAvHhvV0PnOb+T65+j8oFH8sg2L8MoFoiSHF6oJ/cvyEhlGKHENvUnBvSrTOFZnpEHLeg8tjcfdpe8EeOXDeeCXFeikESga8qg71xhft6j/nId3HfX7K6f6Dhvhsn9rBWZB5f7wgy7sdVV7fcr7uUY1KZhrjOVFKhr4lIe88V0LHjklvDTKgD/RNmPqKN9XFTFf9w=,iv:qtb21BUhezRF+wMyUl9pLmRKzgCrrFFeZLPUSR/jCfg=,tag:xVWYIDUI8wOrAkDrNn+czg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT0NVaUp1OTc0dUhSQkly
            N0ZCWmRKbWR3N2MzQXZ5am9vMmhmTlpXdm1RCnBlMFVzNDJ6cWx2OTl3V2s4OWI3
            TWM5eEpCMDdabkZERmpQU0VMK3VaMzQKLS0tIDVBVVRUU3JhUHcwYnlvVDdvOXZH
            QUw0UzdWekgzSURneGlLMG5GNWUwUjAKhIpkU6Dxk0pRgUSLaP3PJH05z+l7/BIg
            ysaGjhQ6bFGoItNEXfSjq6w6B59FxJ+64XbGHjjnKEaJKCrrVmcjvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13rglp49t3fzw0q4wq2n9y4g4dgsdv3nc5tzwetnrzjc4nx3z3gwqnd2nzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:30:25Z"
    mac: ENC[AES256_GCM,data:2PSYdZffZd9/l0LGiqyd4N3nbKN4YtJuXKjW1e4gRc5d5SzF9IEoVz355SRfC5glo8ewnxxdMz9wWN2zvVRQR7eFW+GZqDDcdqxmtHv9LcLzrcm+Yhrqzj7zl638XRDYijHllHkYVZb1OmoTPTDmoc0dGwTt/7/YK6AWQhIIQk4=,iv:KOL/fzbRUg9hrDPgK1+ZDPmvcg6/2WUXXSmDKMSc4Iw=,tag:OF6blPvz0zjT/IjoIjmEjQ==,type:str]
    version: 3.13.3
