apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:iBbLybLSBC3CMy90,iv:E/aX2PPVxD+LnUFoWBkbANCht3mOs6IsvUw15iK3C7c=,tag:E8prEClw5IaJuVDLcfAgrg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:PPX5ihIPKI08KHe/sDInhg==,iv:WdwsxApA45SviwFMtY20iY8SXCMMUW9mIC383VlNEqc=,tag:ATkHDvZaHAM6zWjfVVODvw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Z3NXczJER3NUZEQwOXBx
            U3UzVzNGYWVweGI5ZVRzRGNZcVV0OUlPYldJClJoYUl3Q2I2ZDNMV2dMMGF6RnR3
            Y3RKRUNZYnhWK0ROZHM5TExGdkYvQVUKLS0tIHByYUlOUUFLNUNheDRtY04weU9n
            L3dJeFZ4UVU2dWFlamdqak9VZTB2TG8KAAuWlAiM4SXxQG816oa0OB1wKznINWOJ
            Z7cJ/fweLYtw3XlqGXXHkhywj2Sz1zrcLs/OtCGniyIX0dcafZC30A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13rglp49t3fzw0q4wq2n9y4g4dgsdv3nc5tzwetnrzjc4nx3z3gwqnd2nzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:30:25Z"
    mac: ENC[AES256_GCM,data:VmhuSuaUsh36QApPP8dVehQMMMtMdBS37ff0w2QpJDUKATIxpaUKLA9mSSwisYTWx5OoheqfGf60JHeeEWZOqCY6fgO8krNqSGpFt52kkDKbIo0sXbmWj3ecKLF+7OTCZqAmEpqIFamvh1QYigi0T44GCWd02MS2tYMhaL4EWws=,iv:S+XdmtKqkO5Paw3HhuMLl4yUExuKaFVBlQcfNNGciuU=,tag:KqHXC4JLU4KGX9c8RuA68g==,type:str]
    version: 3.13.3
