apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3-credentials
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:BY9iOf87WzMeDtBDwXQ7ZdofrE4=,iv:13Dm6cPVF12PIsnGhJdxbXDYKVga17E/ajaoNQR3gBs=,tag:Q8mxqd60SMU2l2zH628ECA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:uYf0moKHLpdZ+sNNBaJ9leM7xUjoJxrq+Am0XrXGKFUOtWBll67azg==,iv:dmIrWx6rv0BkXG1+FjudySf2G/Zgb2LyM/JpwTLnUgA=,tag:ZmP/xY8Gt1+kBTXsbqbxEA==,type:str]
sops:
    age:
        - recipient: age19fd7xlck0r3645chqjxq2m22qmtmatr4g0yghplsm33cn5yq7fuq69734h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYUdtYWFNL3BPdlZnYmZp
            SitlZnNZMFF3Ri80d1FwMUF2d3dzUzJNZ2xNCmoxaVNGMjE0SHNJR0Q5cnQ4UytQ
            SDU2cGZNNGJwMDJSQkUxQkllb3AyeEkKLS0tIEozNVZEVGNzaDZkYVluQ0s4SERx
            Z1VzNDFDRVFCbWhUQXBoRGZKTkpUYmMK4nN3snKtGkhDHa9Er0otZO8ylm12huX/
            dhUal4N8CzGfUfyY4R3QZ+oRI/U7U6PejK6O4P6u0bJL0pSzRrA9Vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T18:55:52Z"
    mac: ENC[AES256_GCM,data:VtcmC5Ro81wM4VY9dmfMd5yCpH7fpsL4S/IYoXPOr2Lcuc9dV4XUGQbSlAqaywElzFggnTrmAb2cWRLEqh8HsdyhAoiqA60A0jo+fHyvtMRJzgH9p6qiXIAnEpt1awmqtKpIXH5Sj/4reICLuo+AwhaGdFc/bSX5iACSGWH0fyI=,iv:VBGV3AkMtgPaiKi0qa6Tyf/tJ9xgEjgvQr7M8UZ+2T0=,tag:yxKLh1RPTFOPtk21rHLc0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
