apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3-credentials
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Z9sqU5xIYnTASjc6n6HdEncQUvU=,iv:9SvFNsx87LLfvl+Adn0PVg+OjMxYBVJGm0ya/TUucBQ=,tag:8mSGtx0qv2nI9ReRrIz2Rw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:DqiC+EmIQLXlUKT6L/DM4hUW0Oo1yYtCJy3Qrl+E4qntkyD9UydTRg==,iv:MYWk1CUzi+ZfxSN6LIVDpBO3sEUvon+j0Ix9F25Bfy0=,tag:LxG0jEGO/Cr/dxvAQnEE8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1czNGZTd5SG1ESzRHNi92
            MHdHM0l4ZDVNc293NlBMaGVpcnpuMGU4VXhFClkrTWwwWDZEVnVWTFV0S1pLN0tV
            amM4UW1JMnlnSWh2QTk1N25ucExtL2sKLS0tIDBQRjFqNHIxaEppTnpyTGMzMElv
            S0Q4Z1R5R0kyVEFEcVp5UHpwUHpqN0kK8xXebxUhS+pWO8clyKaXuqjSKs8mz3f5
            2Vu4BWYiJYwhxqbiyVFpQTbqHXZF4C2O5ZVUGnbLXekzUgD6RC0ZyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13rglp49t3fzw0q4wq2n9y4g4dgsdv3nc5tzwetnrzjc4nx3z3gwqnd2nzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:30:24Z"
    mac: ENC[AES256_GCM,data:SYHmSVykkOVbOq2p7MyrffoGaw1dNceupI63b5GHGbcoaBMl9YStv7hERm+/i+PFDr1l+oj5x5r+LnRNe2g56gQCohMJV7xYRSx2AoU3OvMWFcZMUWbUSzoMH5fYpUIqBW4LE5+1XqKATSa+ry3VxvjGVYLdXSAp4IkFA405PDs=,iv:nIsJPp3fuGgKcDVT+p9vAHnMlcT0wO/StY4adbmlyqQ=,tag:9rfH5rgS6MGNJwAiOERnEw==,type:str]
    version: 3.13.3
