apiVersion: v1
kind: Secret
metadata:
    name: cnpg-app-user
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:NCKV,iv:G6uL+RWethRihXeDU/jjabAQ29f20nKwwwNvpNf1pkE=,tag:l/m929D1lSfn3LNW0QWvJQ==,type:str]
    password: ENC[AES256_GCM,data:uctK3dBB2RxR+6HNnYclIujQ+zXvGlTgOxYao8rqtTg=,iv:NtRkLkupCNMPI5RMuUspuRAj/m+Wcld/1f5LneL/E9Q=,tag:dJvWH56xoWXGqyZ7xkdUeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y3ZleFcrUGpmRzgwUjY2
            TkFSemxaY01iK3crY3NBL2FlZEJqbnRqa2lBCkdjN0g3MC9YcnArYzROdVZlY0Fi
            dUd1Y2Q4SktrTDFhZHVheHBCcHd6ckUKLS0tIFZVMkpNU2RneVlVbVovcVUxNTlW
            RSs3TkpkZWZwM2poSEx2OGFrRHU5NHMKEQjR+2d8d22l2/O3nDXDc5fchNKc5M7y
            p5h6wxBgnRKEKvNf48CqSETQmArwMktRewudNvR/7JKKm+05yqLLkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13rglp49t3fzw0q4wq2n9y4g4dgsdv3nc5tzwetnrzjc4nx3z3gwqnd2nzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:30:24Z"
    mac: ENC[AES256_GCM,data:Eec3b9BcZh+oKzrgf3rrwFICCQjY1+0sB3nBiDyb2R3SsBLehAFyhL9jrG6NLAjX9rn0GJ2o7/0KehkJSPPrdSXdi7Ov+w5bJJw7lQMYZRwMdTCIouEQNbUqzudmhSqZMQcpcUzBHGaclLIJxedlEmAAFZDaycA9ex2KI020QRA=,iv:ZtFggnexAFZoEhV9wFpuseY+MX3+kI91/kAbYXhg9Pw=,tag:ZdLfa/54/+Ng13NCdAkTxA==,type:str]
    version: 3.13.3
