apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-cluster
resources:
  - ../../base/cnpg-cluster
  - cnpg-backup-s3-credentials.sops.yaml
  - cnpg-app-user.sops.yaml
  - pgadmin-secret.sops.yaml
  - pgadmin-tls-secret.sops.yaml
  - pgadmin-ingress.yaml
