apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:C8WmKNm/vGLUkc7ecxCABe0=,iv:BrLtm93WRcq9sajSYXcD5OvYuFTuuJdnfR/pqgEWZpA=,tag:i8emvxfWhJG2LKPu7vVuvw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:dKB3ko7/jPhMXjg89BmstWPRZ+zNT4QqLBdI7OZsXgQ=,iv:eGsB9QGmRMyvEgwuQhl7Oo+Z99jHR+UIakrHNbGwfMA=,tag:bGYjTpKFKcL0X/wrEEk9Dg==,type:str]
sops:
    age:
        - recipient: age19fd7xlck0r3645chqjxq2m22qmtmatr4g0yghplsm33cn5yq7fuq69734h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUanB4NlVaUjJHV1RhNk1P
            dEk1bUNEU0xwNGREeWRjY2Ric2pBTDVHajFFCmd0alNqQzB1bUlHUURvWjRXNVk2
            YmJaakdIZzJ6NXJ3Yi9PSm5pZkhvY28KLS0tIDRoaURXbGkxMUZTQlcvYk9qMzdu
            T0pZaHMzSmZ2TEoxT0FnenpFMDNLSW8KND4lpdSRODw2ImIED2cs2rIdcoKZ1+n9
            ZcOdHth9AUAydSOHFSJwIhK+VtuwGBxffSXpMwdeJijwUabftthDXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T18:55:52Z"
    mac: ENC[AES256_GCM,data:BCas95Vyf6o4j60erKHRM6qYQGTvBwOriGLCiYOd5/KRsXpXAbOAZiQujNXg6UCuzizBdkzkDA84JcVrctHZH+os9lzuDSXY/4665KDI0v8W+K5hJ8X+8zIE/FrGIv9omsdszsWcnKEJNgCLre1MiUcutNajuSadbsyV+BhGtP0=,iv:JdYsApl/iwzGNvjhhw3cJWv/Yaq4YqrSomUjmByRhEo=,tag:sqPEJZqaR6F9PIgFt28p/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
