apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:hXrHwFjFoqg6BP+7wG67ZWQ=,iv:Y6xZ08qrVJldjM9vmYfmXr3N+okD1sVrSz4sQnfNiVc=,tag:qGBonNWJcDvqKtvHiExYNQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:rNlJtq3Rh3QxGNZ0aJR45cin8IMSWjYrRUoeQDDHedk=,iv:TUc8QlifAJ+vsPy3fDv75ULogpSrTu4Y7O6IxFzD0J4=,tag:ABBLzUiOqpb/2E2rYp6cSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONWxRRlg1aXptRmRBcWdD
            elRpSXd6eXFPdjd6MnIyNHkrQkVKck04TkVVCmtmY3FRQlhzenpHVjYzVDdrbkFv
            bjMxRndzenRwTzkrTGgydGhMcVJhTmcKLS0tIHhIRFpWRW4wQkpMV3lNUWZtai95
            RjQ3eThGaEpkcHQ2dUV1ZmhROC9hTmMKcndhX5DMvJK4BjOZHbtiYPeppKaTs3TE
            oi+d41CPOY1BvuWF8Bf8WDsNCJw+ux+2wl6MH6pNFbDffM0AkuB34g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13rglp49t3fzw0q4wq2n9y4g4dgsdv3nc5tzwetnrzjc4nx3z3gwqnd2nzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:30:24Z"
    mac: ENC[AES256_GCM,data:7l6qxCHZloDmwzAyfyXmwXMaF+wabOhtHYXgw2w0fAX9UDHeAjvGTrCJYpssp7LT9VYNwiHTmf7xDPrTFkr9q4yjAEENe+cX2QG0xqefY0U5HfVxTpwGpG6M8utcHMMJU1wQVyJUOpzHVLxEny5vRJNowZNQ/8htfBlf5oLItJ8=,iv:+wfHrbiiS/6N/Xus6PaUKQxbFqYV6Rf9I0n4fof1RI8=,tag:EinBAI5sH5QbCNYIXwV09Q==,type:str]
    version: 3.13.3
