apiVersion: v1
kind: Secret
metadata:
    name: grok-bot-webhook-auth
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:LAxo7ZD9UUIRw89VvYupYQKVYuERyNmCTT+G+GLHLOqYvR6JLayDkMrPRLBeIfqvjXrQ1V2MxVtBY0+ROlk7ec9bL9SR,iv:IiJMO7IBu3rvfIvZnVLBtvHBlq+0bjOxN52pmKZcDkM=,tag:K7f7f0roPMZLbzhJjs90AA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaGxzRXFmNHZVY3NMb21j
            TVBGdTV4MG0wWjlpb3ZRRGtnREFyK0RlNm5FClFaT0VSQjhVRVlmbHhXbDZkZ1d6
            aHNJNGxvQXJxZEFjWjBpNlhESHRDdm8KLS0tIDBJaXNYaEl3NFk3TVpqUytoTEJv
            Mms0NGxWeEp2SUFaRzdWVnFyT0VxOE0KTy9FsrPs4CHNKnrhWx7vJEWedn/kXWws
            dcDX41dJ8nKfdi/ft54uqhaI0Ioj2ll3+2HS9cQI3XwunyPK5gLXOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19fd7xlck0r3645chqjxq2m22qmtmatr4g0yghplsm33cn5yq7fuq69734h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T08:50:50Z"
    mac: ENC[AES256_GCM,data:2Lg0wnzhtCAQX5TL7ceHopv8tlVRD/rgD2bNZYR8wCDpFfA2Gi0goyXgN93ZxcS81SxoH9q5zPYTh03yLPzZ1rvoibuZeQn6fiw8avHYcscI86bqCfk25NsJcqcg7ki0iXFQvjBMirVnn7FV7vJz3QZiPumN2tVQmhueqp/xhFI=,iv:C6l6sNHXXNqNQynCBHhWXvKT1yAnP1Qp+4SZ4lBc6nI=,tag:3bTLsP+eRMZfejoEnGza7A==,type:str]
    version: 3.13.3
