apiVersion: v1
kind: Secret
metadata:
    name: grok-bot-webhook-auth
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:x4V+UWG0GPyItkwDDrmkAq3IuUa7AnJblcuMJNmqvbJXVe6cLYM23z4ePq7GsJuX9l92ynIKQ18BttdtF5Slef1yuWp/,iv:z9OO6tJ2zfL/f7uX3+UCqj0991MNseZr4lwHcjNxWbo=,tag:j5ZTRP9kfS31SUweG8aLmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MTlpOVRjT2xaSUJWc0dF
            a0MwK0NqMnEvdEUrMkhpU0xCamc0c1lmbUN3CktFbndUUjNjTjJTcWgvS1ptVEtn
            dGJTYWE1cG04Rk8zUTZQNzBRTE43TFEKLS0tIHpic0ZKZkZLZWdIbkJtaTNVMWMw
            ZVpCc2lBVW5FT2QzZE5vOVZWQ2gwUkUKTennfJduBWRorkUW9m9qYYsJ2h5KAvOn
            IRHk3N40gc+u/pB3fOldBD9Kg5pi5dnbnoU9NjX44VEuqQ5jJ64dFA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13rglp49t3fzw0q4wq2n9y4g4dgsdv3nc5tzwetnrzjc4nx3z3gwqnd2nzl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T14:30:25Z"
    mac: ENC[AES256_GCM,data:gdSKibzAjMcoHw5OooHx/ssym6r7OcqswYWV6rDBYueYzceohFYceriP4Oh5kcZkplL8YDpUGVdvP4XmNMwSuk4b6Z7Q+TvKO0re4RnvqO0jgaWfKlIn4V+8jDFZ/l0ntwoQl17TqbpHWqCbme1BoqGmsR/83EKyLBpKI1a2kns=,iv:p3yg0/hdkqOay0QpyxVooIjnG7hkdScAffxX5FH7Qyg=,tag:nqesw2Yfj21c7HbChrfDrw==,type:str]
    version: 3.13.3
