apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana-tls-secret.yaml
  - grok-bot-webhook-auth.sops.yaml
  - grok-bot-webhook.yaml
  - raspberry-pi-node-alerts.yaml
